on:
    workflow_dispatch:

jobs:
    actions-job:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              uses: .github/actions/Greeting@v1 ###actions/checkout@v7.0.1  ###owner-name-refer commit
              with:
                  name: Khaled
              env:
                  GITHUB_TOKE: ${{secrets.GITHUB_TOKEN}}

                  
              
