on:
  workflow_dispatch:
    inputs:
      environment: 
        description: "Choose Environment"
        required: true
        default: "Staging"
        type: choice
          - Staging
          - Production
          


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy applicaiton
        run: echo "Deploy application manual"
