on:
    push:
        branches:
            - main
            - "release/**"  ### any branch begins with release
        paths:
            - "src/**"  ## do not run CI/CD on mistake documenation -- only inside src folder 
    pull_request:
        branches:
            - main
            - "release/**"  
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v7
        
        - name: Run tests
          run: npm test